[package]
name = "copy"
version = "0.1.0"
edition = "2024"

[dependencies]
num-traits = "0.2.19"


[[test]]
name = "01_tests" # Name your test target
path = "copy_test/src/main.rs" # Point to the main file for this test target
