[package]
name = "tic_tac_toe"
version = "0.1.0"
edition = "2024"

[dependencies]
[[test]]
name = "01_tests" # Name your test target
path = "tic_tac_toe_test/src/main.rs" # Point to the main file for this test target
